import {DEFAULT,PRESETS,render,wavBytes,normalized} from './synth.js';
let state=normalized(DEFAULT), ctx=null, source=null, clean=false, selected=-1;
const $=s=>document.querySelector(s), pathCanvas=$('#path'), scope=$('#scope');
const ids=['root','duration','spread','sub','bite','drive','tail'];
const names=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
function fmt(id,v){if(id==='root')return `${names[v%12]}${Math.floor(v/12)-1}`;if(id==='duration')return `${(+v).toFixed(2)}s`;if(id==='spread')return `${v}¢`;return `${v}%`}
function size(c){const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);if(c.width!==Math.round(r.width*d)||c.height!==Math.round(r.height*d)){c.width=Math.round(r.width*d);c.height=Math.round(r.height*d)}return {w:c.width,h:c.height,d}}
function drawPath(){const {w,h,d}=size(pathCanvas),g=pathCanvas.getContext('2d');g.clearRect(0,0,w,h);g.strokeStyle='#292925';g.lineWidth=1*d;for(let y=1;y<5;y++){g.beginPath();g.moveTo(0,h*y/5);g.lineTo(w,h*y/5);g.stroke()}g.strokeStyle='#d9ff39';g.lineWidth=2*d;g.beginPath();state.path.forEach((p,i)=>{const x=p[0]*w,y=(1-p[1])*(h-28*d)+14*d;i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke();state.path.forEach((p,i)=>{const x=p[0]*w,y=(1-p[1])*(h-28*d)+14*d;g.fillStyle=i===selected?'#e24b2d':'#0e0e0d';g.strokeStyle='#d9ff39';g.lineWidth=2*d;g.fillRect(x-7*d,y-7*d,14*d,14*d);g.strokeRect(x-7*d,y-7*d,14*d,14*d);g.fillStyle='#8c8b80';g.font=`${8*d}px monospace`;g.textAlign='center';g.fillText(String(i+1).padStart(2,'0'),x,y-11*d)})}
function drawScope(){const audio=render(state,clean),{w,h,d}=size(scope),g=scope.getContext('2d');g.clearRect(0,0,w,h);g.strokeStyle='#34342f';g.beginPath();g.moveTo(0,h/2);g.lineTo(w,h/2);g.stroke();for(const [ch,color,off] of [[audio.left,'#ecebdd',-.5],[audio.right,'#e24b2d',.5]]){g.strokeStyle=color;g.globalAlpha=.8;g.lineWidth=1*d;g.beginPath();for(let x=0;x<w;x++){const i=Math.floor(x/w*ch.length),y=h/2+ch[i]*h*.34+off*d;x?g.lineTo(x,y):g.moveTo(x,y)}g.stroke()}g.globalAlpha=1;$('#readout').textContent=`${clean?'CLEAN':'DRIVEN'} / ${audio.left.length} SAMPLES`}
function sync(){ids.forEach(id=>{const el=$(`#${id}`);el.value=state[id];$(`#${id}-o`).textContent=fmt(id,state[id])});drawPath();drawScope()}
function stop(){if(source){try{source.stop()}catch{}source=null}$('#status').textContent='stopped.'}
async function strike(){stop();ctx ||= new AudioContext({sampleRate:48000});await ctx.resume();const a=render(state,clean),b=ctx.createBuffer(2,a.left.length,a.sampleRate);b.copyToChannel(a.left,0);b.copyToChannel(a.right,1);source=ctx.createBufferSource();source.buffer=b;source.connect(ctx.destination);source.onended=()=>{source=null;$('#status').textContent='ready.'};source.start();$('#status').textContent=`playing ${clean?'clean':'driven'} / ${state.duration.toFixed(2)}s`;}
ids.forEach(id=>$(`#${id}`).addEventListener('input',e=>{state[id]=id==='duration'?+e.target.value:parseInt(e.target.value);document.querySelectorAll('[data-preset]').forEach(x=>x.classList.remove('active-job'));sync()}));
function point(e){const r=pathCanvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;return {x,y}}
pathCanvas.addEventListener('pointerdown',e=>{const p=point(e);selected=state.path.reduce((best,q,i)=>Math.abs(q[0]-p.x)<Math.abs(state.path[best][0]-p.x)?i:best,0);pathCanvas.setPointerCapture(e.pointerId);document.body.classList.add('dragging');state.path[selected][1]=Math.max(0,Math.min(1,1-p.y));sync()});
pathCanvas.addEventListener('pointermove',e=>{if(selected<0)return;const p=point(e);state.path[selected][1]=Math.max(0,Math.min(1,1-p.y));drawPath();drawScope()});
pathCanvas.addEventListener('pointerup',()=>{selected=-1;document.body.classList.remove('dragging');drawPath()});
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{state=normalized(PRESETS[b.dataset.preset]);document.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('active-job',x===b));sync();strike()}));
$('#strike').addEventListener('click',strike);$('#stop').addEventListener('click',stop);
const cleanBtn=$('#clean');cleanBtn.addEventListener('pointerdown',()=>{clean=true;cleanBtn.setAttribute('aria-pressed','true');sync()});const release=()=>{clean=false;cleanBtn.setAttribute('aria-pressed','false');sync()};cleanBtn.addEventListener('pointerup',release);cleanBtn.addEventListener('pointerleave',release);
$('#copy').addEventListener('click',async()=>{await navigator.clipboard.writeText(JSON.stringify(state));$('#status').textContent='recipe copied.'});
$('#paste').addEventListener('click',async()=>{try{const x=JSON.parse(await navigator.clipboard.readText());if(!Array.isArray(x.path)||x.path.length!==8)throw Error();state=normalized(x);sync();$('#status').textContent='recipe loaded.'}catch{$('#status').textContent='invalid recipe.'}});
$('#export').addEventListener('click',()=>{const bytes=wavBytes(state,false),url=URL.createObjectURL(new Blob([bytes],{type:'audio/wav'})),a=document.createElement('a');a.href=url;a.download=`bitepath-${state.root}-${state.duration.toFixed(2)}s.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);$('#status').textContent=`exported ${(bytes.length/1024).toFixed(1)} KB WAV.`});
addEventListener('resize',sync);sync();
window.__BITEPATH={getState:()=>normalized(state),setState:x=>{state=normalized(x);sync()},bytes:()=>wavBytes(state,false),render:()=>render(state,false),strike,stop};
